# Generated by Django 4.2.19 on 2025-03-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='ИНН')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Общая информация')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет арендатора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер помещения')),
                ('floor', models.CharField(choices=[('1', '1 этаж'), ('2', '2 этаж'), ('3', '3 этаж'), ('4', '4 этаж'), ('5', '5 этаж'), ('6', '6 этаж'), ('7', '7 этаж'), ('8', '8 этаж')], max_length=2, verbose_name='Этаж')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь (кв.м)')),
                ('status', models.CharField(choices=[('rented', 'В аренде'), ('free', 'Свободно'), ('reserved', 'В резерве')], default='free', max_length=10, verbose_name='Статус')),
                ('lease_start', models.DateField(blank=True, null=True, verbose_name='Дата начала аренды')),
                ('lease_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания аренды')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='TenantFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='tenants/files/', verbose_name='Файл')),
                ('uploaded_by', models.CharField(max_length=255, verbose_name='Добавил')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Файл арендатора',
                'verbose_name_plural': 'Файлы арендаторов',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
            },
        ),
    ]
