# Generated by Django 4.2.19 on 2025-03-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tenantfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='core.tenant', verbose_name='Арендатор'),
        ),
    ]
